############################
#  Volumes (shared state)  #
############################
volumes:
  images:          # raw downloaded files (downloader ⇄ embedder)
  es-data:         # persistent Elasticsearch data

############################
#  Services                #
############################
services:
  # ---------- Vector store -----------------------------------------------
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=true        # enables dense_vector + ANN
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g   # tune heap for your laptop
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs ${ES_HOST:-http://localhost:9200}/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Image-Downloader -------------------------------------------
  downloader:
    build:
      context: .                     # repo root (can see common/)
      dockerfile: downloader/Dockerfile
    depends_on:
      - es
    env_file: .env
    volumes:
      - images:/data/images                # shared volume
      - ./data/image_urls.txt:/data/image_urls.txt:ro
    healthcheck:
      # exit 0 if PID 1 (main loop) is alive
      test: ["CMD-SHELL", "test -e /proc/1"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3

  # ---------- Embedding-Generator ----------------------------------------
  embedder:
    build:
      context: .                     # repo root
      dockerfile: embedder/Dockerfile
    depends_on:
      es:
        condition: service_healthy
    env_file: .env
    volumes:
      - images:/data/images
    healthcheck:
      # exit 0 if PID 1 (main loop) is alive
      test: ["CMD-SHELL", "test -e /proc/1"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3

  # ---------- Search API --------------------------------------------------
  search-api:
      build:
        context: .                          #  ← repo root
        dockerfile: search_api/Dockerfile   #  ← same file you already have
      env_file: .env
      ports:
      - "${API_PORT:-8000}:8000"    # host:container
      volumes:
        - images:/data/images:ro
      depends_on:
        es:
          condition: service_healthy
      healthcheck:
        test: ["CMD-SHELL", "curl -f ${API_HOST:-http://localhost:8000}/healthz || exit 1"]
        interval: 5s
        timeout: 3s
        start_period: 40s                   # ← give Uvicorn & ES client time
        retries: 5
  
  # ---------- Web UI ------------------------------------------------------
  ui:
    build: ./ui
    depends_on:
      search-api:
        condition: service_healthy
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "curl -fs ${STREAMLIT_HOST:-http://localhost:8501}/ || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s    # UI starts fast
      retries: 3
